### ISSUE TITLE
사전에 발음기호 빠짐

### ISSUE THREAD

**Issue by WhistlerHusky** [khris/naver-endic-unofficial#13]
Firefox 버전 사용중인데 발음기호도 사전에 있으면 좋을거 같아요.

**Comment by khris** [comment]
메일을 지금 확인했네요. 제보 감사합니다. 발음기호도 표시하도록 해보겠습니다.

**Comment by WhistlerHusky** [comment]
아직 파이어폭스 등록은 안되었네요. 방금 최신 버전 다운로드해서 파폭에 적용해봤는데 잘되네요
감사합니다~! ^^
![image](https://user-images.githubusercontent.com/10891407/37791948-d88dc8b0-2de0-11e8-85f5-abb4e5963cbb.png)

**Comment by khris** [comment]
@WhistlerHusky 몇가지 다른 사항을 더 살펴볼게있어서 릴리즈를 보류하고 있었습니다. 확인 감사드립니다.
