### ISSUE TITLE
사전 내용이 안뜨는 현상

### ISSUE THREAD

**Issue by ghost** [khris/naver-endic-unofficial#15]
18년 7월 11일 현재,

키를 누르고 사전을 띄우면 흰색 창은 뜨는데, 내용이 아무것도 나오지를 않네요.

windows 10, windows 7에서 문제 확인했습니다.

windows 7의 경우 기존에 잘 동작했었습니다.

네이버 사전 쪽에서 정보를 못가져 가게 막은 걸까요? 바뀐 걸까요? 확인 부탁드립니다.

**Comment by khris** [comment]
보안관련 문제로 뜨지 않는 것으로 보입니다. 수정하여 1.1.1을 릴리즈 했습니다.

해결이 안되셨다면 다시 이 이슈를 열어주세요.
