### ISSUE TITLE
 Dark Mode   Add-on과 같이 사용시 내용이 안보입니다.

### ISSUE THREAD

**Issue by happylarrykim** [khris/naver-endic-unofficial#16]
안녕하세요 유용한 플러그인 만들어 주셔서 너무 잘 사용하고 있습니다.

단 https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/ 와 같이 사용시 내용이 전혀 보이지 않아서 불편합니다.

혹시 이부분도 수정이 가능할까요?

**Comment by khris** [comment]
이슈를 지금봤네요. 확인 후 처리하도록 하겠습니다.

**Comment by khris** [comment]
해결되었습니다. 내일이나 모레 올라갈 다음 버전에 포함 될 것입니다.
