### ISSUE TITLE
CORS 에러

### ISSUE THREAD

**Issue by cosine0** [khris/naver-endic-unofficial#24]
네이버에서 이제 외부 요청 막으려고 하는지 검색 시 CORS 에러가 나네요. 다른 URL이나 중계서버 등이 필요할 듯합니다.

**Comment by hjyoon** [comment]
잘 쓰고 있었는데 왜 안되나 했더니 CORS 문제였네요.

**Comment by khris** [comment]
요즘 바빠서 지금에야 알았습니다. 금방 고치도록 하겠습니다 ㅠㅠ

**Comment by khris** [comment]
많이 늦었습니다. 방금 문제가 수정된 버전을 업데이트 했습니다. 항상 사용해주셔서 감사합니다.
