### ISSUE TITLE
사용 시, 빈 상자가 출력됩니다.

### ISSUE THREAD

**Issue by hjyoon** [khris/naver-endic-unofficial#27]
![not-working](https://user-images.githubusercontent.com/16138767/176865573-2fef47c8-af3b-45e0-aee9-f3458fbfdcf0.jpg)

https://en.dict.naver.com/api3/enko/search?query=lucrative&m=pc&range=all&shouldSearchVlive=true&lang=ko
GET 요청이 아무 응답을 못 받는 거 같은데 확인 부탁드립니다.

**Comment by khris** [comment]
수정되었습니다. 곧 릴리즈 하겠습니다.
